<script type='text/javascript'>

$( document ).ready(function() {
  // Handler for .ready() called.
	postState = $('#stateValue').val();
	postCountry = $('#countryValue').val();
	initCountry('US');
  
});

	$(function(){
		$('#Clientselect').change(function(){
			var value = $('#Clientselect').val();
			if(value != 0){
				window.location.href='/add-edit-client/'+value;
			}
		});
		
		$('#clientgroupname').change(function(){
			var value = $('#Clientselect').val();
			//alert($('#Clientselect').val());
			if(value != 0){
				window.location.href='/add-edit-client/'+value;
			}
		});
		
		
	function split( val ) {
      return val.split( /,\s*/ );
    }
    function extractLast( term ) {
      return split( term ).pop();
    }
$(function()
	{
		$('#clientgroupname').autocomplete(
    	{
        	source: "/ajax?method=Client",
        	minLength: 2,
        	select: function(event, ui) {
        		$('#client_street_1').val(ui.item.street1);
        		$('#client_street_2').val(ui.item.street2);
        		$('#client_street_3').val(ui.item.street3);
        		$('#client_city').val(ui.item.city);
        		$('#client_state').val(ui.item.state);
        		$('#client_zip').val(ui.item.zip);
        		$('#client_phone').val(ui.item.phone);
				$('#client_phone_ext').val(ui.item.phone_ext);
				$('#client_fax').val(ui.item.fax);
        		$('#client_primary_contact').val(ui.item.primary_contact);
        		$('#client_id').val(ui.item.id);
        		$('#client_email').val(ui.item.email);
        		$('#product_advertiser').val(ui.item.company);
        		$('#split_agreement').val(ui.item.split_agreement);
        		$('#split_percent').val(ui.item.split_percent);
        		$('#client_country').val(ui.item.country);
        	}
    	});
        $('#clientgroupname').keyup(function(){
    		if(e.which != 13){
    			$('#client_street_1').val('');
        		$('#client_street_2').val('');
        		$('#client_street_3').val('');
        		$('#client_city').val('');
        		$('#client_state').val('');
        		$('#client_zip').val('');
        		$('#client_phone').val('');
        		$('#client_contact').val('');
        		$('#client_id').val('');
        		$('#client_email').val('');
        		$('#client_country').val('');
        	}
    	}
	);
	$('#clientgroupname').focus();
	});
    });	
  </script>

			<div style='float:right; overflow-y:scroll; height:350px; margin-top:20px;'>
	<h3>Client List <? if($this->editClient){ ?>
		(<a href="/add-edit-client/<?=$user->id;?>" style='color:#000;'>Create New Client</a>)
		<? } ?></h3>
	
		<? foreach($this->allClients AS $user){ ?>
		<a href="/add-edit-client/<?=$user->id;?>"  style='color:#000;'><div   class='user_block' style='width:350px; padding:3px;'><?=$user->company;?></div></a>
		<? } ?>
	</div>
<? if($this->editClient){ ?>
	<h1>Edit Client #<?=$this->editClient->id;?> (<?=$this->editClient->email;?>)</h1>
<? } else { ?>

	<h1>Create a Client</h1>
<? } ?>
<form method='post' action=''>
	<table>
	
		<tr>
			<td>
				<b>Client Group</b><br />
				<select id='group' name='group'  >
				<option value="Select">Select Client Group</option>
					<? foreach($this->clientGroups AS $item){ ?>
						<option value="<?=$item['id'];?>" <? if($this->data['group'] == $item['id'] || $this->data['group'] == $item['clientgroupname'] ){ echo "selected"; } ?>><?=$item['clientgroupname'];?></option>
					<? } ?>
				</select>
			</td>
		</tr>
	
		<tr>
			<td>
				<b>Company*</b><br />
				<input type='text' id='company' name='company' value="<?=$this->data['company'];?>">
			</td>
			<td>
				<b>Email*</b><br />
				<input type='text' name='email' value="<?=$this->data['email'];?>">
			</td>
		</tr>
		<tr>
			<td>
				<b>Primary Contact</b><br />
				<input type='text' name='primary_contact' value="<?=$this->data['primary_contact'];?>">
			</td>
			<td>
				<b>URL/Website</b><br />
				<input type='text' name='url' value="<?=$this->data['url'];?>">
			</td>
		</tr>
		<tr>
			<td>
				<b>Street Address 1</b><br />
				<input type='text' name='street1' value="<?=$this->data['street1'];?>">
			</td>
			<td>
				<b>Street Address 2</b><br />
				<input type='text' name='street2' value="<?=$this->data['street2'];?>">
			</td>
		</tr>
		<tr>
			<td>
				<b>Street Address 3</b><br />
				<input type='text' name='street3' value="<?=$this->data['street3'];?>">
			</td>
			<td>
				<b>City</b><br />
				<input type='text' name='city' value="<?=$this->data['city'];?>">
			</td>
		</tr>
		
		<tr>
			<td>
				<b>Country </b></br>
				<select id='country' name='country' onchange='populateState();'>
				</select>
			</td>
			<td>
				<b>State</b><br />
				<select id='state' name='state'>
				</select>
			</td>
			
		</tr>
		<input type='hidden'  id="stateValue" value="<?=$this->data['state']; ?>">
		<input type='hidden'  id="countryValue" value="<?=$this->data['country']; ?>">
		<input type='hidden'  name='user'    id="user" value="<?=$this->data['user']; ?>">
		
		<tr>
			<td>
				<b>Zip Code</b><br />
				<input type='text' name='zip' value="<?=$this->data['zip'];?>">
			</td>
			<td>
<!--<b>Split Percent</b><br />-->
			<input type='hidden' tabindex="3" onkeypress="numbersOnly(event);" name='split_percent' id='split_percent' style='width:30px;' value="<? if($this->data['split_percent']){ echo $this->data['split_percent'];  } else { echo "0";  } ?>"><span style='font-size:20px;'></span>
				<b>Phone</b><br />
				<input type='text' name='phone' value="<?=$this->data['phone'];?>">
			</td>
		</tr>
		
		<tr>
			<td valign='top'>
				<b>Ext</b><br />
				<input type='text' name='phone_ext' value="<?=$this->data['phone_ext'];?>">
			</td>
			
			<td valign='top'>
				<b>Fax</b><br />
				<input type='text' name='fax' value="<?=$this->data['fax'];?>">
			</td>
			
			
			<tr>
			
			<td valign='top'>
				
			</td>
			
			<td>
	
			<!--<b>Split With</b><br />
			<select tabindex="3" name='split_agreement' id='split_agreement'>
				<option value="">Choose a Media Broker</option>
				<? foreach($this->users AS $user){ ?>
					<option value="<?=$user->id;?>" <? if($this->data['split_agreement'] == $user->id){ echo "selected"; } ?>><?=$user->name;?></option>
				<? } ?>
			</select-->

			</td>
			
			</tr>
			
		</tr>
	</table>
	<br />
	<? if($this->editClient){ ?>
		<input type='hidden' name='method' value='update'>
	<? } else { ?>
		<input type='hidden' name='method' value='create'>
	<? } ?>
	
	<? 
	   /*if(!isset($this->rows))
			$rows =  2;	
	   else
			$rows = $this->rows;*/
	
	?>
	
	<!--<a href="/add-edit-client/<?#=$user->id;?>/<?#=$rows + 1;?>" style='color:#000;'>Add Row</a>
	<a href="/add-edit-client/<?#=$user->id;?>/<?#=$rows - 1;?>" style='color:#000;'>Remove Row</a>-->
	
	<table width='100%' border='1' style='border-collapse: collapse;'>
	<tr style='text-align:center;'>
		<td>SNo</td>
		<td>Contact Name</td>
		<td>Email Id</td>
		<td>Phone No</td>
		<td>Phone Ext</td>
		<td>Fax No</td>
	</tr>
	<? $i = 1;
		while($i < 11){ 
		//public function addRow(){
		?>
			<tr style='text-align:center;'>
			
				<td><?=$i;?></td>
				
				<input type='hidden' tabindex="4" name="id_<?=$i;?>" value="<?=$this->data['id_'.$i]; ?>">
				
				<input type='hidden' tabindex="4" name="client_id_<?=$i;?>" value="<?=$this->data['client_id_'.$i]; ?>">
				
				<td><input type='text' tabindex="4" class='name small' name="name_<?=$i;?>" value="<?=$this->data['name_'.$i]; ?>"></td>
				
				<td><input type='text' tabindex="4" class='email small' name="email_<?=$i;?>" value="<?=$this->data['email_'.$i]; ?>"></td>
				
				<td><input type='text' tabindex="4" class='phone small ' name="phone_<?=$i;?>" value="<?=$this->data['phone_'.$i]; ?>"></td>
				
				<td><input type='text' tabindex="4" class='phone_ext small ' name="phone_ext_<?=$i;?>" value="<?=$this->data['phone_ext_'.$i]; ?>"></td>
				
				<td><input type='text' tabindex="4" class='fax small' name="fax_<?=$i;?>" value="<?=$this->data['fax_'.$i]; ?>"></td>
				
				</td>
				
			</tr>
		<? 
			$i++;
		}
		
		
		
	?>

</table>
	
	
	<input type='submit' value='Save Client'>
</form>
<br />
<? if($this->editClient){ ?>
<script type='text/javascript'>
	function deleteUser(){
		//var sure = confirm("Delete this client? This cannot be undone.");
		//if(sure){
			$('#delete_form').submit();
		//} else {
		//	return false;
		//}
	}
</script>
<form method='post' action='' id='delete_form'>
	<input type='hidden' name='method' value='delete'>
		
		<input type='button' value='Delete Client'  style='background:#8E0009; border:0;' onClick="deleteUser();">;
	</form>
<? } ?>