<div style='text-align:center;'>
	<div class='box' style='margin:auto; width:370px;'>
		<h1>Employee Login</h1>
		<hr />
		<form method='post' action=''>
			<table>
				<tr>
					<td>Email</td>
					<td><input type='text' name='email' ></td>
				</tr>
				<tr>
					<td>Password</td>
					<td><input type='password' name='password' ></td>
				</tr>
			</table>
			<input type='hidden' name='goto' value="<?=@$_GET['goto'];?>">
		<input type='submit' value="Login">
		</form>
	</div>
</div>