<h1>Admin : Markup Category</h1>
<form method='post' action=''>
<br>
<!-- style="width:150px;"-->
<!--<center>
<table>
	<tr>
	<td></td>
	<td align="center"><b>Commission</b></td>
	<td align="center"><b>Bonus</b></td>
	</tr>
	<tr>
		
	
		<td>Bronze</td><td><input type='text' id='bronze' name='bronze' value='<?=$this->data['bronze'];?>' size='4'></td><td><input type='text' id='bronze_bonus' name='bronze_bonus' value='<?=$this->data['bronze_bonus'];?>' size='4'></td>
	</tr>
	<tr>
		<td>Silver</td><td><input type='text' id='silver' name='silver' value='<?=$this->data['silver'];?>' size='4'></td><td><input type='text' id='silver_bonus' name='silver_bonus' value='<?=$this->data['silver_bonus'];?>' size='4'></td>
	</tr>
	<tr>
		<td>Gold</td><td><input type='text' id='gold' name='gold' value='<?=$this->data['gold'];?>' size='4'></td><td><input type='text' id='gold_bonus' name='gold_bonus' value='<?=$this->data['gold_bonus'];?>' size='4'></td>
	</tr>
	<tr>
		<td>Platinum</td><td><input type='text' id='platinum' name='platinum' value='<?=$this->data['platinum'];?>' size='4'></td><td><input type='text' id='platinum_bonus' name='platinum_bonus' value='<?=$this->data['platinum_bonus'];?>' size='4'></td>
	</tr>
	<tr>
		<td>Diamond</td><td><input type='text' id='diamond' name='diamond' value='<?=$this->data['diamond'];?>' size='4'></td><td><input type='text' id='diamond_bonus' name='diamond_bonus' value='<?=$this->data['diamond_bonus'];?>' size='4'></td>
	</tr>
	<tr>
		<td>Minimum Order Total ($)</td><td><input type='text' name='min_total' value='<?=$this->data['min_total'];?>' size='4'></td><td><input type='text' id='min_percentage' name='min_percentage' value='<?=$this->data['min_percentage'];?>' size='4'></td>
	</tr>
		
</table><br />
<input type='submit' value='Save Changes'>
</center>-->

<center>
<table>
	<tr>
	<td></td>
	<td align="center"><b>Commission</b></td>
	<td align="center"><b>Bonus</b></td>
	</tr>
	<tr>
		
	
		<td>Bronze</td><td><input style="width:150px;" type='text' id='bronze' name='bronze' value='<?=$this->data['bronze'];?>' size='4'></td><td><input style="width:150px;" type='text' id='bronze_bonus' name='bronze_bonus' value='<?=$this->data['bronze_bonus'];?>' size='4'></td>
	</tr>
	<tr>
		<td>Silver</td><td><input style="width:150px;" type='text' id='silver' name='silver' value='<?=$this->data['silver'];?>' size='4'></td><td><input style="width:150px;" type='text' id='silver_bonus' name='silver_bonus' value='<?=$this->data['silver_bonus'];?>' size='4'></td>
	</tr>
	<tr>
		<td>Gold</td><td><input style="width:150px;" type='text' id='gold' name='gold' value='<?=$this->data['gold'];?>' size='4'></td><td><input style="width:150px;" type='text' id='gold_bonus' name='gold_bonus' value='<?=$this->data['gold_bonus'];?>' size='4'></td>
	</tr>
	<tr>
		<td>Platinum</td><td><input style="width:150px;" type='text' id='platinum' name='platinum' value='<?=$this->data['platinum'];?>' size='4'></td><td><input style="width:150px;" type='text' id='platinum_bonus' name='platinum_bonus' value='<?=$this->data['platinum_bonus'];?>' size='4'></td>
	</tr>
	<tr>
		<td>Diamond</td><td><input style="width:150px;" type='text' id='diamond' name='diamond' value='<?=$this->data['diamond'];?>' size='4'></td><td><input style="width:150px;" type='text' id='diamond_bonus' name='diamond_bonus' value='<?=$this->data['diamond_bonus'];?>' size='4'></td>
	</tr>
	<tr>
		<td>Minimum Order Total ($)</td><td><input style="width:150px;" type='text' name='min_total' value='<?=$this->data['min_total'];?>' size='4'></td><td><input style="width:150px;" type='text' id='min_percentage' name='min_percentage' value='<?=$this->data['min_percentage'];?>' size='4'></td>
	</tr>
		<tr>
		<td></td>
		<td colspan="2" align="center"><input type='submit' value='Save Changes'></td>
		</tr>
</table><br />

</center>
</form>